export const menuItems = [
    {
        title:'HOME',
        url:'/',
        cName:'nav-links'
    },
    {
        title:'PORTFOLIO',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'PAGES',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'ELEMENTS',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'SHOP',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'BLOG',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'CONTACT',
        url:'/contacts',
        cName:'nav-links'
    }
] 